name: Test
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
          pip freeze
      - name: Run checks
        run: |
          make check
